import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/ui/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import BrandingDashboardWidget from "@/components/widgets/branding";
import {
  MenuHederDashboardWidget,
  MenuUpgradeWidget,
  SidebarMenuDashboardWidget,
} from "@/components/widgets/menu";

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
      <div className="hidden border-r bg-muted/40 md:block">
        <div className="flex h-full max-h-screen flex-col gap-2">
          <BrandingDashboardWidget />
          <SidebarMenuDashboardWidget />
          <div className="mt-auto p-4 sticky">
            <MenuUpgradeWidget />
          </div>
        </div>
      </div>
      <div className="flex flex-col">
        <MenuHederDashboardWidget />
        {children}
      </div>
    </div>
  );
}
